version: '3.8'

services:
  eb-due:
    build:
      context: ./backend
      dockerfile: Dockerfile.coolify.simple
    container_name: eb-due-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - eb-due-network
    volumes:
      - ./backend/data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: eb-due-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-eb_due_db}
      - POSTGRES_USER=${POSTGRES_USER:-eb_due_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - eb-due-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-eb_due_user} -d ${POSTGRES_DB:-eb_due_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  eb-due-network:
    driver: bridge 